### ISSUE TITLE
Has  this version of python3's ssd  completed?

### ISSUE THREAD

**Issue by zhuangruowang** [jkjung-avt/ssd-caffe#1]
The previous ssd-caffe was written in python2 , i would to use python'3 version.Could author tell me how long it would be finished?
Thx

**Comment by jkjung-avt** [comment]
Yes, this version of ssd-caffe works for python3.

I took the code from https://github.com/weiliu89/caffe/tree/ssd and made necessary modifications to make it work under python3. I've trained a few SSD models with it already.

**Comment by zhuangruowang** [comment]
Appreciate it
